version: '3'

tasks:
  default:
    cmds:
      - task: run

  proto:
    desc: Generate protobuf files
    cmds:
      - protoc --go_out=. proto/spiral.proto
      - go mod tidy
      - go mod vendor

  build:
    desc: Build the spiral generator
    deps: [proto]
    cmds:
      - go build -o bin/spiral cmd/spiral/main.go

  run:
    desc: Run the spiral generator with default settings
    deps: [build]
    cmds:
      - ./bin/spiral -imag=6300000.0 -output=spiral.png -save-proto=spiral.pb

  run-downsampled:
    desc: Run with default downsampling
    deps: [build]
    cmds:
      - ./bin/spiral -imag=6300000.0 -output=spiral_downsampled.png -save-proto=spiral_downsampled.pb -downsample=true -aggressive=0.5

  run-aggressive:
    desc: Run with aggressive downsampling
    deps: [build]
    cmds:
      - ./bin/spiral -imag=6300000.0 -output=spiral_aggressive.png -save-proto=spiral_aggressive.pb -downsample=true -aggressive=4.0

  compare-compression:
    desc: Generate and compare different compression methods
    deps: [build]
    cmds:
      # Generate full spiral with all compression methods
      - ./bin/spiral -imag=6300000.0 -output=spiral_full.png 
        -save-proto=spiral_full.pb 
        -save-delta=spiral_full.delta 
        -save-msgpack=spiral_full.msgpack
      # Generate downsampled spiral with all compression methods
      - ./bin/spiral -imag=6300000.0 -output=spiral_downsampled.png 
        -save-proto=spiral_downsampled.pb 
        -save-delta=spiral_downsampled.delta 
        -save-msgpack=spiral_downsampled.msgpack 
        -downsample=true -aggressive=0.5
      # Generate aggressively downsampled spiral with all compression methods
      - ./bin/spiral -imag=6300000.0 -output=spiral_aggressive.png 
        -save-proto=spiral_aggressive.pb 
        -save-delta=spiral_aggressive.delta 
        -save-msgpack=spiral_aggressive.msgpack 
        -downsample=true -aggressive=4.0
      # Compare file sizes
      - |
        echo "Compression size comparison:"
        echo "Full spiral:"
        ls -lh spiral_full.{pb,delta,msgpack} | awk '{print $5, $9}'
        echo "\nDownsampled spiral:"
        ls -lh spiral_downsampled.{pb,delta,msgpack} | awk '{print $5, $9}'
        echo "\nAggressively downsampled spiral:"
        ls -lh spiral_aggressive.{pb,delta,msgpack} | awk '{print $5, $9}'

  clean:
    desc: Clean build artifacts and generated files
    cmds:
      - rm -f bin/spiral
      - rm -f spiral*.png
      - rm -f spiral*.pb spiral*.delta spiral*.msgpack
      - rm -rf vendor/
      - rm -f proto/spiral.pb.go

  generate-all:
    desc: Generate all spiral variants with all compression methods
    deps: [build]
    cmds:
      - task: compare-compression 